# Generated by Django 2.0.7 on 2018-08-07 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180807_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='acitve',
            new_name='active',
        ),
    ]
